### PR TITLE
adding blacklisting for light-dom nodes in sl-gallery

### PR DESCRIPTION
**Pull request by kyzrfranz**
Hey, feel free to check out - seems like the tests are broken (couldn't get them to run on my machnie).
Hence I added an extra section in the demo.

Maybe we could make this even more elaborate, and use selectors in combination with whitelisting/blacklisting?

### CODE REVIEW

**Comment by jsilvermist** [comment]
Hmm what's your opinion on blacklisting vs whitelisting for this? If we only whitelist `sl-gallery-image` nodes, wouldn't that be enough? What case would you have where you need something else whitelisted?

**Comment by jsilvermist** [comment]
For example, something like:
```js
this._images = [...info.target.children].filter(el => el.nodeName === 'SL-GALLERY-IMAGE');
```

Also, tests seem to be running fine on my end, is it possible you have Java newer than Java 8 installed on your machine?

**Comment by kyzrfranz** [comment]
In terms of black vs white I also feel that whitelisting is the better aproach here.
My practical case is that I am using iron-image instead of yours, as it comes with some features I like to use.
If you allow for whitelisting, it could be useful for people like me - but I understand if you dont want to allow it.

Regarding the tests I need to check again as I had a bunch of docker containers running. Java9+ shouldnt be it I think

**Comment by jsilvermist** [comment]
Hmm I'm hesitant to encourage using other types of nodes since in the next large update for the gallery supporting touch, swiping, pinching, zoom etc. I may want to add more dynamic data to the image element itself, keeping per-image processing on the image element instead of the general gallery.

I do agree something has to be done to support using `dom-if` and `dom-repeat` so I think I'll merge this for now and offer a patch release, but I'm not sure what the long term road plan for this will be yet.

**Comment by kyzrfranz** [comment]
Sounds good to me for now, I could offer to integrate the features I am missing into sl-image...

**Comment by jsilvermist** [comment]
Which features are you referring to?

**Comment by kyzrfranz** [comment]
For one, I'd love a sizing property like in iron-image ('contain', 'cover' ....) and also a preload option with placeholders. Also I am thinking about using ```<picture>``` internally to allow for more responsiveness. Let me know what you think

**Comment by jsilvermist** [comment]
@kyzrfranz `background-size` is set on `:host`, so you can easily overwrite it as `contain` or whatever else you may want using css selecting the `sl-gallery-image` element. I feel it's better to leave styling in CSS instead of creating attributes for each case.

For using `<picture>` I'm currently undecided on how to support this, but more responsiveness is always nice.

Sorry for the delay responding, I had hoped to implement support for using `<picture>` earlier, but have been quite busy with life so haven't had a chance to do much work on this yet.

**Pull request merged**
